# Generated by Django 5.0 on 2024-10-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_category_post_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
