# Generated by Django 5.0 on 2024-10-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pics/')),
            ],
        ),
    ]
