# Generated by Django 5.0 on 2024-11-06 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_posted'], 'verbose_name_plural': 'Comments'},
        ),
    ]
