# Generated by Django 5.0 on 2024-11-06 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_posted']},
        ),
    ]
