# Generated by Django 5.0 on 2024-11-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('about', models.TextField()),
            ],
        ),
    ]
